SFR-1828_APIS3ObjectLink
NYPL/drb-etl-pipeline pull request #278
Opened 2023-12-14 21:04 UTC by mitri-slory

This PR adds a new API that returns the object url for S3 objects from the DRB buckets on AWS. The commented out section was the original process where I was going to use a pre-signed url to access the url. I'm keeping it for now if I might need to use it in the future before this PR is approved. I'll delete them if the current code is good enough.

2023-12-20 03:47 UTC, mitri-slory commented on api/blueprints/drbS3.py
This API was the initial format where the link returned was the object url to the S3 object, but I realized later on that we needed to return a unique link to users so it the url won't be shared amongst users outside the organization.

2023-12-20 03:52 UTC, mitri-slory commented on tests/unit/test_api_s3_blueprint.py
These tests were made with the initial return to an object url I had in mind for the S3 API, so this is outdated.

2023-12-21 21:34 UTC, Apophenia requested changes
Logic is all good, not necessarily a merge blocker but if you could revert the whitespace change in the Swagger JSON that would be perfect.

2023-12-21 21:34 UTC, Apophenia commented on swagger.v4.json
> +        },
```suggestion
        },
```

2023-12-21 21:34 UTC, Apophenia commented on swagger.v4.json
> +        },
If you can revert this whitespace change I think this will be ready to go!

2023-12-21 23:41 UTC, Apophenia approved these changes

2023-12-22 18:40 UTC, merged